blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/stayproof/stayproof-feedback/discussions
    about: Ask questions, share feedback, or discuss features
